### ISSUE TITLE
It gives small linker error

### ISSUE THREAD

**Issue by bnagarjuna** [SummonY/ComChat#1]
ld: warning: directory not found for option '-L/Users/Nagarjuna/Downloads/ComChat-99d011f229644b53a00de3a9b37b5a61ef5146ac/ComChat/ComChat/VoiceConvert/lib'
ld: warning: ignoring file /Users/Nagarjuna/Downloads/ComChat-99d011f229644b53a00de3a9b37b5a61ef5146ac/ComChat/VoiceConvert/lib/libopencore-amrwb.a, missing required architecture x86_64 in file /Users/Nagarjuna/Downloads/ComChat-99d011f229644b53a00de3a9b37b5a61ef5146ac/ComChat/VoiceConvert/lib/libopencore-amrwb.a (3 slices)
ld: warning: ignoring file /Users/Nagarjuna/Downloads/ComChat-99d011f229644b53a00de3a9b37b5a61ef5146ac/ComChat/VoiceConvert/lib/libopencore-amrnb.a, missing required architecture x86_64 in file /Users/Nagarjuna/Downloads/ComChat-99d011f229644b53a00de3a9b37b5a61ef5146ac/ComChat/VoiceConvert/lib/libopencore-amrnb.a (3 slices)
Undefined symbols for architecture x86_64:
  "_Decoder_Interface_Decode", referenced from:
      DecodeAMRFileToWAVEFile(char const_, char const_) in amrFileCodec.o
  "_Decoder_Interface_exit", referenced from:
      DecodeAMRFileToWAVEFile(char const_, char const_) in amrFileCodec.o
  "_Decoder_Interface_init", referenced from:
      DecodeAMRFileToWAVEFile(char const_, char const_) in amrFileCodec.o
  "_Encoder_Interface_Encode", referenced from:
      EncodeWAVEFileToAMRFile(char const_, char const_, int, int) in amrFileCodec.o
  "_Encoder_Interface_exit", referenced from:
      EncodeWAVEFileToAMRFile(char const_, char const_, int, int) in amrFileCodec.o
  "_Encoder_Interface_init", referenced from:
      EncodeWAVEFileToAMRFile(char const_, char const_, int, int) in amrFileCodec.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

please help me how to solve....

**Comment by SummonY** [comment]
Bugs have been fixed!
